### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'setup/theme/penguin-theme.json'

### ISSUE THREAD

**Issue by mikwee** [alvarosabu/slidev-theme-penguin#38]
When I try to run my presentation with this theme, I get this error:
```
node:fs:448
    return binding.readFileUtf8(path, stringToFlags(options.flag));
                   ^

Error: ENOENT: no such file or directory, open 'setup/theme/penguin-theme.json'
    at Object.readFileSync (node:fs:448:20)
    at /home/testuser/Documents/MLP-Icon/penguin/setup/shiki.ts:6:44
    at evalModule (/home/testuser/Documents/MLP-Icon/node_modules/.pnpm/jiti@1.21.3/node_modules/jiti/dist/jiti.js:1:247443)
    at jiti (/home/testuser/Documents/MLP-Icon/node_modules/.pnpm/jiti@1.21.3/node_modules/jiti/dist/jiti.js:1:245256)
    at loadSetups (file:///home/testuser/Documents/MLP-Icon/node_modules/.pnpm/@slidev+cli@0.49.10_@babel+parser@7.24.7_@nuxt+kit@3.11.2_rollup@4.18.0__@types+markdown-it@1_2g3sziss434bdggz3wwan7b4m4/node_modules/@slidev/cli/dist/chunk-LOUKLO2C.mjs:12:70)
    at loadShikiSetups (file:///home/testuser/Documents/MLP-Icon/node_modules/.pnpm/@slidev+cli@0.49.10_@babel+parser@7.24.7_@nuxt+kit@3.11.2_rollup@4.18.0__@types+markdown-it@1_2g3sziss434bdggz3wwan7b4m4/node_modules/@slidev/cli/dist/chunk-SRWMA3GA.mjs:7878:24)
    at createMarkdownItShiki (file:///home/testuser/Documents/MLP-Icon/node_modules/.pnpm/@slidev+cli@0.49.10_@babel+parser@7.24.7_@nuxt+kit@3.11.2_rollup@4.18.0__@types+markdown-it@1_2g3sziss434bdggz3wwan7b4m4/node_modules/@slidev/cli/dist/chunk-SRWMA3GA.mjs:9360:5)
    at createMarkdownPlugin (file:///home/testuser/Documents/MLP-Icon/node_modules/.pnpm/@slidev+cli@0.49.10_@babel+parser@7.24.7_@nuxt+kit@3.11.2_rollup@4.18.0__@types+markdown-it@1_2g3sziss434bdggz3wwan7b4m4/node_modules/@slidev/cli/dist/chunk-SRWMA3GA.mjs:9301:26)
    at ViteSlidevPlugin (file:///home/testuser/Documents/MLP-Icon/node_modules/.pnpm/@slidev+cli@0.49.10_@babel+parser@7.24.7_@nuxt+kit@3.11.2_rollup@4.18.0__@types+markdown-it@1_2g3sziss434bdggz3wwan7b4m4/node_modules/@slidev/cli/dist/chunk-SRWMA3GA.mjs:9590:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'setup/theme/penguin-theme.json'
}

Node.js v20.13.1
ELIFECYCLE  Command failed with exit code 1.
```
No matter what I try, even cloning the repo, it doesn't work. What could be going on?
Thanks.

**Comment by mikwee** [comment]
Update: I saw that you need `vite-svg-loader`. I installed that and put it in the config, and nothing changed. So it's not that.

**Comment by Piotr-Zin** [comment]
Also having this issue

**Comment by RyanMulready** [comment]
This theme only works if you clone this repo; you can no longer install it as a dependency.

**Comment by fdtl01** [comment]
The same problem!
